menu:
  Home: /
  Archives: /archives
  Type: /maiqingcheng
  Reading: /reading
  About: /about
  rss: /atom.xml

excerpt_link: Read More #摘要链接文字
archive_yearly: false #按年存档

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

blogrolls: #友情链接
  - bruce sha's duapp wordpress: http://ibruce.duapp.com


archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: maiqingcheng

google_analytics:
favicon: /favicon.ico
